### ISSUE TITLE
ASUS bios resolution glitch

### ISSUE THREAD

**Issue by mallendeo** [pikvm/docs#4]
Hi!

There is a bug/glitch with ASUS bios when using the TC358743 chip (I'm using the Lusya bridge). My guess is because the "low" resolution (720p).

<img width="961" alt="Screen Shot 2020-02-02 at 12 32 42" src="https://user-images.githubusercontent.com/1578018/73610621-1feac500-45b8-11ea-8fa6-1a2de43e0f84.png">

Is there any way to force the hdmi stream at 1080p at lower framerates?

Thanks!

**Comment by mdevaev** [comment]
One of the users told me about a similar problem, but I don't know how to solve it yet. I think I had a motherboard somewhere with a similar BIOS. I'll see if something can be done in this case.

PS: Does this BIOS have the option to enable the legacy interface without graphcs?

**Comment by mallendeo** [comment]
The bios doesn't have that option afaik. I also searched for an older bios version to flash but it seems they all comes with the UEFI menu.

PS: This is what I tried without luck

`/etc/kvmd/override.yaml`

```yaml
kvmd:
    streamer:
        cap_pin: -1
        cmd:
            - /usr/bin/ustreamer
            - --device=/dev/kvmd-video
            - --persistent
            - --format=uyvy
            - --encoder=omx
            - --glitched-resolutions=720x480,720x576
            - --workers=4
            - --quality={quality}
            - --desired-fps={desired_fps}
            - --resolution=1920x1080
            - --drop-same-frames=30
            - --last-as-blank=0
            - --unix={unix}
            - --unix-rm
            - --unix-mode=0660
            - --exit-on-parent-death
            - --process-name-prefix={process_name_prefix}
            - --no-log-colors
        desired_fps: 15
        max_fps: 15
        quality: 50
        state_poll: 1.0
        timeout: 2.0
```
